title: Lynette Bye
description: AI journalism, productivity coaching, and research-backed advice.
url: "https://lynettebye.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
permalink: /blog/:year/:month/:day/:title
header_pages:
  - journalism.md
  - coaching.md
  - blog-index.md
  - contact.md
markdown: kramdown
